### ISSUE TITLE
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'

### ISSUE THREAD

**Issue by Ravikumar028** [yezz123/Nectus#38]
Getting this issue while trying to run the project. please help. couldn't find help from stackoverflow also. thanks.

**Comment by yezz123** [comment]
let me just check the configuration of what cause the error

**Comment by Ravikumar028** [comment]
I'm using python3.9 in mac os

**Comment by Ravikumar028** [comment]
if i remove .env file, it is working in production mode. also DB values are hardcoded. Flask app is ignoring main.py and runs app folder.
